const API_BASE_URL_DEVELOPEMENT = ' https://localhost:7099';
const API_BASE_URL_PRODUCTION = 'https://dotnettodoserver.azurewebsites.net';

const ENDPOINTS = {
    GET_ALL_TODOS: '/get-all-todos',
    GET_ALL_TODOS_BY_ID: '/get-todo-by-id',
    ADD_TODO: '/add-todo',
    DELETE_TODO: '/delete-todo-by-id',
    UPDATE_TODO: '/update-todo',
};
 
const developement = {
    API_URL_GET_ALL_TODOS: `${API_BASE_URL_DEVELOPEMENT}${ENDPOINTS.GET_ALL_TODOS}`,
    API_URL_GET_ALL_TODOS_BY_ID: `${API_BASE_URL_DEVELOPEMENT}${ENDPOINTS.GET_ALL_TODOS_BY_ID}`,
    API_URL_ADD_TODO: `${API_BASE_URL_DEVELOPEMENT}${ENDPOINTS.ADD_TODO}`,
    API_URL_DELETE_TODO: `${API_BASE_URL_DEVELOPEMENT}${ENDPOINTS.DELETE_TODO}`,
    API_URL_UPDATE_TODO: `${API_BASE_URL_DEVELOPEMENT}${ENDPOINTS.UPDATE_TODO}`
} 

const production = {
    API_URL_GET_ALL_TODOS: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.GET_ALL_TODOS}`,
    API_URL_GET_ALL_TODOS_BY_ID: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.GET_ALL_TODOS_BY_ID}`,
    API_URL_ADD_TODO: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.ADD_TODO}`,
    API_URL_DELETE_TODO: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.DELETE_TODO}`,
    API_URL_UPDATE_TODO: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.UPDATE_TODO}`
}

const config = process.env.NODE_ENV === 'development' ? developement : production;

export default config;